# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  researchapi:
    image: researchapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5276:5276
